# data
INPUT_SIZE = 128
INPUT_CHANNELS = 1
DATASET_SIZE = 16392
NUM_CLASSES = 10
ITEMS_PER_IMAGE = (2, 5)

# network
NUM_CELLS = 4
BOXES_PER_CELL = 2
FULLY_CONVOLUTIONAL = True
USE_SIGMOID = True

# training
LEARNING_RATE = 1e-3
BATCH_SIZE = 64
EPOCHS = 10

# loss
LAMBDA_COORD = 10
LAMBDA_OBJ = 1
LAMBDA_NO_OBJ = 2
LAMBDA_PROB = 2

# inference and statistics
TEST_NUM_ITEMS = 32
TEST_CONFIDENCE_THRESHOLD = 0.7
STATS_NUM_ITEMS = 4096
STATS_IOU_THRESHOLDS = [i / 10 for i in range(3, 10)]
